### ISSUE TITLE
license of the leaflet-rs crate

### ISSUE THREAD

**Issue by mkroehnert** [slowtec/leaflet-rs#10]
Hello, I have a question related to the license of the leaflet-rs crate.

Currently the readme says 'copyright by slowtec', but no explicit license is specified and  the repo contains no license.txt file.
This means that it is currently not allowed to re-use the code in another project.

However, the crates.io page however states that the crate is available as MIT or Apache-2: https://crates.io/crates/leaflet.

Could you please clarify if the crates.io metadata is correct?
And if so, would it be possible to add the missing license terms to the repository?

Thanks in advance

**Comment by flosse** [comment]
Thanks for your feedback! It's of course allowed to re-use it!
I just added the two license files.

**Comment by mkroehnert** [comment]
@flosse great, thank you very much for the fast feedback and reaction.
