### ISSUE TITLE
Paths outdated?

### ISSUE THREAD

**Issue by pkopparla** [slowtec/leaflet-rs#11]
This readme here https://github.com/slowtec/leaflet-rs/tree/master/examples/basic says to go to src/example, but there is no such directory. How do I run the example?

**Comment by flosse** [comment]
Just ignore that line `cd src/example` if you're already in the example folder :)

And feel free to open a PR to fix the README ;-)
Thanks!

**Comment by halas** [comment]
@pkopparla you should be in the directory `src/examples/basic`
From there run first 
`wasm-pack build --target web`
then, when this command finishes running
`https` (assuming that before you installed `https` crate running `cargo install https` from whatever directory. 
Then you should see working example at http://localhost:8000 (without path)

**Comment by pkopparla** [comment]
Thanks @halas, that works! One minor thing: the path was `LEAFLET-RS/examples/basic`, there is no `example` under `src`. This typo is also in `example/pkg/README.md`.

**Comment by halas** [comment]
Right, sorry, updated the comment to have correct path. Happy you got it working :)
