### ISSUE TITLE
Usage of Map.on

### ISSUE THREAD

**Issue by TehUncleDolan** [slowtec/leaflet-rs#14]
Hi,

Thanks for this binding 🙏 
I'm currently trying to wrap my head around the usage of [`Map::on`](https://docs.rs/leaflet/latest/leaflet/struct.Map.html#method.on) :/

The part that's bugging me is the type of the `handler`: a `JsValue`.
How can I pass a Rust closure as `JsValue` here?

I couldn't find any example and I'm a bit lost.

Any pointer are welcome :)

**Comment by TehUncleDolan** [comment]
Ok, found the doc of [`Closure`](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen/closure/struct.Closure.html#), which implements `AsRef<JsValue>`.

**Comment by chriamue** [comment]
Just for documentation, maybe someone has a better solution:

```rust
pub enum Msg {
    MapClicked(LatLng),
}
// ...
let container: Element = document().create_element("div").unwrap();
let container: HtmlElement = container.dyn_into().unwrap();
container.set_class_name("map");
let leaflet_map = Map::new_with_element(&container, &JsValue::NULL);

let message:Callback<LatLng> = ctx.link().callback(Msg::MapClicked);
let cb: Closure<dyn FnMut(MouseEvent)> = Closure::wrap(Box::new(move |e: MouseEvent| {
    message.emit(e.latlng());
}));
leaflet_map.on("click", &Closure::into_js_value(cb));
```
