### ISSUE TITLE
What version of leaflet is supported ?

### ISSUE THREAD

**Issue by DataHearth** [slowtec/leaflet-rs#18]
Hey!

I was wondering what version of `leaflet.js` is supported with the latest release.

It might be useful to add a small line in the `README.md` to tell what version (`leaflet-rs`) supports as `leaflet.js`. 

Thanks!

**Comment by flosse** [comment]
The last version I used was `v1.6.0`.
Feel free to open a PR!
Thx!

**Comment by DataHearth** [comment]
Yup ! I can definitely to it ^^. I'm gonna do it next week-end 🙂

**Comment by emirror-de** [comment]
Hi,

would it be an option for you to directly integrate the supported version into the library? Maybe behind a feature flag like `embed-source`?
This would enable the user to serve the leaflet files from their own server, having this library on both sides, front- and backend and automatically compatible with each other.

API example:

`lib.rs`
```rust
#[cfg(feature = "embed-source")]
fn javascript_source() -> String;
#[cfg(feature = "embed-source")]
fn css_source() -> String;
```

**Comment by flosse** [comment]
I would not recommend to embed the source because the WASM file size would increase. Why not use [rust-embed](https://docs.rs/rust-embed/) on the server?

**Comment by flosse** [comment]
I just tried to use the `basic` example with `v1.7.1`, `v1.8.0` and `v1.9.3` and all worked fine. So I think we can close this issue.
