### ISSUE TITLE
`OptionParser` error when running the `yew-component` example

### ISSUE THREAD

**Issue by Luke-ebbis** [slowtec/leaflet-rs#19]
Hello,

I am considering using `leaflet` on a project of mine, and after trying out the example I find that there is some error when I build the project using `trunk serve`. I get the following error:
```
2023-06-23T13:57:35.251842Z  INFO using system installed binary app=sass version=Ruby Sass 3.7.4
2023-06-23T13:57:35.251874Z  INFO compiling sass/scss path="scss/style.scss"
2023-06-23T13:57:35.349207Z  INFO copying generated wasm-bindgen artifacts
OptionParser::InvalidOption: invalid option: --no-source-map
Did you mean?  sourcemap
  Use --trace for backtrace.
2023-06-23T13:57:35.405603Z ERROR ❌ error
error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: sass call returned a bad status
```
I am running
* `sass` 3.7.4
* `trunk` 0.16.0.

Is there anything I can do to resolve this issue?

**Comment by flosse** [comment]
The problem seems to be `invalid option: --no-source-map`, so I can't imagine that this relates to `leaflet-rs`.

**Comment by lucasalavapena** [comment]
Both examples work just fine for me. I also have trunk 0.16.0. I do not think I have sass directly  installed, I think trunk comes with https://github.com/sass/dart-sass based on the docs.

**Comment by Luke-ebbis** [comment]
Thank you for the response. I will re-install trunk and try again.
