### ISSUE TITLE
Merge `leaflet` from `leptos-leaflet`

### ISSUE THREAD

**Issue by emirror-de** [slowtec/leaflet-rs#23]
Hi there,

[leptos-leaflet](https://github.com/emirror-de/leptos-leaflet/tree/main) has in my opinion a clearer structure and more bindings available than this crate.

Are you interested in merging the changes into your crate? `leptos-leaflet` could then rely on `leaflet-rs` instead of having a separate fork.

If you are happy to merge, I could set up a pull request for it if you do not find the time to do.

Best regards,
Lewin

**Comment by flosse** [comment]
@emirror-de thanks for this suggestion!
It sounds very promising and I am all the more thrilled that you are already offering a PR :smile: 

Thank you very much in advance!

**Comment by emirror-de** [comment]
I am currently working on a PR. Are you happy when I change the API from `camelCase` to `snake_case` to get the code more rusty?

For example:
```rust
let map = Map::new(...);
map.add_control(...); // instead of map.addControl
```

**Comment by flosse** [comment]
> I am currently working on a PR.

:+1:

> Are you happy when I change the API from `camelCase` to `snake_case` to get the code more rusty?

Absolutely! It's a shame I didn't do this before :see_no_evil:
