### ISSUE TITLE
How to bundle leaflet?

### ISSUE THREAD

**Issue by Natureshadow** [slowtec/leaflet-rs#24]
For autonomous self-hosting and in order to embrace user privacy, loading Leaflet from an external CDN should be avoided.

Is there some standard mechanism in Rust WASM land to bundle such resources with the build, like `vite` or other bundlers do in NPM/JavaScript?

**Comment by flosse** [comment]
I'd recommend to just download the JS and serve it with your webserver.

> Is there some standard mechanism in Rust WASM land to bundle such resources with the build, like vite or other bundlers do in NPM/JavaScript?

It depends on your project setup.
If you're building a single page application you should have a look at [trunk](https://trunkrs.dev/)
or the slightly better maintained fork [trunk-ng](https://ctron.github.io/trunk/).
If you're building a server you might be interested in [rust-embed](https://github.com/pyrossh/rust-embed).

**Comment by Natureshadow** [comment]
Great, thanks!

And as I understand it, I could just tell trunk to do an `npm install` as a `pre_build` hook, then reference files from `node_modules` from my `index.html`.
